BEGIN{FS="[;:]"; OFS=" "}
$1=="DTSTART"{DTSTART=$NF}
$1=="DTSTART"{TZID=$2}
$1=="SUMMARY"{SUMMARY=$3$4$5$NF}
$1=="LOCATION"{LOCATION=$3}
$1=="END"{
	if ($2=="VEVENT")
		print DTSTART,TZID":",SUMMARY,LOCATION
}
